### ISSUE TITLE
Messages.txt parsing

### ISSUE THREAD

**Issue by aalbino2** [PDI-Berlin/EPIC_scraper#3]
Hey @haltugyildirim,

while parsing the Messages.txt files, if no growth event is detected there is an error of the parsing instead of an intentional break of the execution:

```python
growth_time(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrea/NOMAD/nomad-FAIR_develop/.pyenv/lib/python3.11/site-packages/epic_scraper/epicfileimport/epic_module.py", line 315, in growth_time
    print(df.grow)
          ^^^^^^^
  File "/home/andrea/NOMAD/nomad-FAIR_develop/.pyenv/lib64/python3.11/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'grow'

```

can you raise some output message in these cases?

Thanks

**Comment by haltugyildirim** [comment]
Now the error should be fixed with the newest commit in line 362/363.

**Comment by aalbino2** [comment]
hey @haltugyildirim for the next issues, can you open a connected pull request so one can easily see what you change?
